### ISSUE TITLE
Icons For Cinnamon

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Artwork/Windows-XP#1]
This icon set is missing some main things:
- Cinnamon Settings Icons
- System Tray Icons
- Sizing for Add/Remove Background Folders

**Comment by Elbullazul** [comment]
In fact it's missing lots of features, but hey, at least it works better :)

Well be working on this further down the road

**Comment by Elbullazul** [comment]
cinnamon settings icons provided, need icons for the following options:
- fonts
- hot corners
- notifications
- graphic tablet
- power

**Comment by Elbullazul** [comment]
added battery icons for cinnamon, possibly gnome & xfce

**Comment by Elbullazul** [comment]
also, folders should scale right when I push the next commit. I have it all ready but github had DNS issues (again?)

**Comment by dominichayesferen** [comment]
Yeah, there's a massive DDoS wave taking down a large part of the web

**Comment by Elbullazul** [comment]
someone should invent anti-ddos mesures...

**Comment by Elbullazul** [comment]
all feature requests added and working:
![screenshot_2016-10-23_17-02-42](https://cloud.githubusercontent.com/assets/15310985/19629397/873d0644-9942-11e6-90f9-b55e618cda29.png)

**Comment by dominichayesferen** [comment]
Awesome, congratulations Elbullazul! This will be looking great in feren OS 2017.0... Now, can you fix Win2-7?

**Comment by Elbullazul** [comment]
@feren that's our next goal

@cinnamoner what do you think of this icon set?

---

maybe now I'll add some mymetipes in WinXP...
