### ISSUE TITLE
Most of the images are broken???

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [B00merang-Artwork/Windows-XP#12]
Take this file for example, it doesn't even work when you open the original in github:
https://github.com/B00merang-Artwork/Windows-XP/blob/master/32x32/mimetypes/gnome-mime-application-pdf.png

This one is in the same directory and is fine for some reason:
https://github.com/B00merang-Artwork/Windows-XP/blob/master/32x32/mimetypes/application-pdf.png

**Comment by dominichayesferen** [comment]
If you're only looking through GitHub, then that's just how GitHub reacts to symbolic links.

Symbolic links are 'items' in a filesystem that redirect read and write requests to their target files or folders. You can see what they point to from GitHub by looking at the 'text' (again, that's just how GitHub represents them) of the file that's shown in GitHub, such as https://github.com/B00merang-Artwork/Windows-XP/blob/master/32x32/mimetypes/gnome-mime-application-pdf.png telling you it points to 'application-pdf.png', which in symbolic links logic is https://github.com/B00merang-Artwork/Windows-XP/blob/master/32x32/mimetypes/application-pdf.png .

Without a path before the filename in the symbolic link's target, it'll just look for said file or folder in the exact same directory as the symbolic link itself in a Linux/UNIX environment (where this icon set is meant to be used).
Therefore, in actual execution these technically work fine.

**Comment by iFUCKINGHATEcomputers** [comment]
thats fuckin weird man
